### ISSUE TITLE
Make a hand out with checklist and better instructions for Module 6 Flume

### ISSUE THREAD

**Issue by joewheaton** [Riverscapes/Fluvial-Geomorphology#6]

**Comment by lauren-herbine** [comment]
I have this saved in a separate document to print, but here it is in case you want for future classes/want to edit: 

## Flume Lab

*Fluvial Geomorphology, Module 6*

Define and/or explain each of the concepts below with text (1-3 sentences) and illustrate your observation of them. Your ‘illustration” can use video(s) with narration and or labels, and/or photos with annotations. If helpful, feel free to hyperlink to other resources.

I would suggest using the numbers below to organize your page into headings and sub-headings.

Items in **bold** are concepts you should make sure you are taking pictures of and/or recording *during* the lab (that should also be explained with accompanying text afterwards). Items not bolded are analyses you can do after the lab. 

### Concepts to Illustrate & Explain

### 1. Flume Controls

How do you control the following with the flume:

- [ ] **1.1** **Q (Water Discharge)** 

- [ ] **1.2** **S (Slope)**

- [ ] **1.3 Qs (Sediment Discharge)**
- [ ] **1.4 Profile**
- [ ] **1.5 Base Level**

### 2. Fluvial Geomorphic Processes

Simulate and record your observations of:

- [ ] **2.1 Bed Erosion**
- [ ] **2.2 Bank Erosion**
- [ ] **2.3 Deposition**
- [ ] **2.4 Sediment Transport**

### 3. Fluvial Geomorphic Mechanisms

Simulate and record your observations of the specific manifestation of fluvial geomorphic processes as these mechanisms of adjustment:

- [ ] **3.1 Grain Size Sorting**
- [ ] **3.2 Meandering**
- [ ] **3.3 Braiding**
- [ ] **3.4 Avulsion**
- [ ] **3.5 Chute Dissection**
- [ ] **3.6 Structural Forcing**

Answer (in up to a paragraph or so and with illustrations if helpful):

- [ ] **3.7** While *meandering* can be observed, were you able to produce a classic single-thread, meandering channel in any of your experiments? If so, explain how it occurred, if not, do you think it is possible with the controls you had at your disposal in this flume?

### 4. Events

Simulate and record your observations of three specific events::

- [ ] **4.1 Small Flood**
- [ ] **4.2 Big Flood**
- [ ] **4.3 Channel Realignment (Grading)**

### Analysis

Answer (in up to a paragraph or so and with illustrations if helpful):

- [ ] **4.4** From what you did, what seems to be the roll/impact of small flood vs. big flood?
- [ ] **4.5** In your experimentation, did you observe *overbank* flows, *bankfull* flows and/or *baseflow* flows?
- [ ] **4.6** What role did hyporehic flow play in what you observed?
- [ ] **4.7** What roll did recession limb flows seem to play in what you observed?
